### ISSUE TITLE
Delete user organizer when clicked on delete button

### ISSUE THREAD

**Issue by samanthakem** [sandiegojs/sdjs-speaker-app#42]
<img width="183" alt="Screen Shot 2020-07-23 at 9 08 04 AM" src="https://user-images.githubusercontent.com/4277045/88310029-0eab8700-ccc4-11ea-9e00-8e7300e0815b.png">

**Comment by nathanhannig** [comment]
For anyone who will work on this.

When the project is set up locally the Organizer role doesn't have `find` permission on Users.

This issue of course will require you to also enable the `destroy` permission as well.
