### ISSUE TITLE
Meetups page not loading

### ISSUE THREAD

**Issue by samanthakem** [sandiegojs/sdjs-speaker-app#44]
When the users goes to the meetup page, it breaks on the `getMeetups` function

**Comment by nathanhannig** [comment]
When navigating to http://localhost:3000/admin/meetups the page appears to load correctly, no errors occur when it hits the endpoint http://localhost:1337/events

The next day it did not work. The Meetup API was returning an error of 
```
"code": "auth_fail",
"message": "Invalid csrf credentials"
```

I opened a Incognito browser and hit the url and it began working again kind of.
https://api.meetup.com/sandiegojs/events?no_later_than=2021-3-19

Not sure if an issue with Meetup?

**Comment by nathanhannig** [comment]
I also noticed a defect in the code where `.getDay` is being used instead of `.getDate` so it was causing the day field to be a 0 when it is a Monday. I wonder if this is making Meetup go crazy in how it responds.
